import json
import os
import sys
import requests
from datetime import datetime

REPORTS_DIR = "/home/server/devsecops-project/reports"
OLLAMA_URL  = "http://localhost:11434/api/generate"
MODEL       = "mistral"

def get_latest_report():
    files = sorted([
        f for f in os.listdir(REPORTS_DIR)
        if f.startswith("zap_report") and f.endswith(".json")
    ])
    if not files:
        print("[!] No ZAP reports found.")
        sys.exit(1)
    latest = os.path.join(REPORTS_DIR, files[-1])
    print(f"[*] Analyzing report: {files[-1]}")
    return latest

def parse_vulnerabilities(report_path):
    with open(report_path) as f:
        data = json.load(f)
    vulns = []
    for site in data.get("site", []):
        for alert in site.get("alerts", []):
            vulns.append({
                "name":     alert.get("name", "Unknown"),
                "risk":     alert.get("riskdesc", "Unknown"),
                "desc":     alert.get("desc", "")[:300],
                "solution": alert.get("solution", "")[:300],
                "instances": len(alert.get("instances", []))
            })
    return vulns

def ask_mistral(vulnerabilities):
    vuln_text = ""
    for i, v in enumerate(vulnerabilities, 1):
        vuln_text += f"""
Vulnerability {i}:
- Name: {v['name']}
- Risk Level: {v['risk']}
- Description: {v['desc']}
- Instances Found: {v['instances']}
- Suggested Solution: {v['solution']}
"""

    prompt = f"""You are a cybersecurity expert analyzing a web application security scan report.

The following vulnerabilities were found by OWASP ZAP scanner:

{vuln_text}

Please provide:
1. A simple explanation of each vulnerability in plain English
2. The potential impact if exploited
3. A specific step-by-step fix for each vulnerability
4. An overall security assessment (score out of 10)
5. Top 3 priorities to fix first

Be specific, practical, and clear. Format your response with clear sections for each vulnerability."""

    print("[*] Sending report to Mistral for analysis...")
    print("[*] This may take 1-2 minutes...")

    response = requests.post(OLLAMA_URL, json={
        "model": MODEL,
        "prompt": prompt,
        "stream": False
    }, timeout=300)

    if response.status_code != 200:
        print(f"[!] Ollama error: {response.status_code}")
        sys.exit(1)

    return response.json().get("response", "No response received")

def save_html_report(vulnerabilities, analysis):
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    file_ts   = datetime.now().strftime("%Y%m%d_%H%M%S")

    vuln_summary = ""
    for v in vulnerabilities:
        color = "#ff4444" if "High" in v['risk'] else "#ff9900" if "Medium" in v['risk'] else "#2196F3"
        vuln_summary += f"""
        <div class="vuln-card">
            <h3 style="color:{color}">{v['name']}</h3>
            <p><strong>Risk:</strong> {v['risk']}</p>
            <p><strong>Instances:</strong> {v['instances']}</p>
        </div>
        """

    # Convert analysis text to HTML paragraphs
    analysis_html = ""
    for line in analysis.split("\n"):
        if line.strip():
            if line.startswith("#") or line.startswith("**"):
                analysis_html += f"<h3>{line.replace('#','').replace('**','')}</h3>"
            else:
                analysis_html += f"<p>{line}</p>"

    html = f"""
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>AI Security Analysis Report</title>
    <style>
        body {{ font-family: Arial, sans-serif; background: #1a1a2e; color: #eee; margin: 0; padding: 20px; }}
        .header {{ background: #16213e; padding: 30px; border-radius: 10px; text-align: center; margin-bottom: 20px; border: 1px solid #0f3460; }}
        .header h1 {{ color: #e94560; margin: 0; }}
        .section {{ background: #16213e; padding: 20px; border-radius: 10px; margin-bottom: 20px; border: 1px solid #0f3460; }}
        .section h2 {{ color: #e94560; }}
        .vuln-card {{ background: #0f3460; padding: 15px; border-radius: 8px; margin: 10px 0; }}
        .analysis {{ background: #0f3460; padding: 20px; border-radius: 8px; line-height: 1.8; }}
        .analysis h3 {{ color: #e94560; }}
        .footer {{ text-align: center; color: #888; margin-top: 20px; }}
    </style>
</head>
<body>
    <div class="header">
        <h1>🤖 AI Security Analysis Report</h1>
        <p>Generated: {timestamp}</p>
        <p>Powered by Mistral 7B via Ollama</p>
    </div>

    <div class="section">
        <h2>📋 Vulnerabilities Found ({len(vulnerabilities)} total)</h2>
        {vuln_summary}
    </div>

    <div class="section">
        <h2>🔍 AI Analysis & Recommendations</h2>
        <div class="analysis">
            {analysis_html}
        </div>
    </div>

    <div class="footer">
        <p>Generated by DevSecOps Pipeline | Mistral 7B | {datetime.now().year}</p>
    </div>
</body>
</html>
"""

    output_path = os.path.join(REPORTS_DIR, f"ai_report_{file_ts}.html")
    with open(output_path, "w") as f:
        f.write(html)
    print(f"[+] ✅ AI report saved: {output_path}")
    return output_path

if __name__ == "__main__":
    report_path   = get_latest_report()
    vulnerabilities = parse_vulnerabilities(report_path)

    if not vulnerabilities:
        print("[*] No vulnerabilities found in report.")
        sys.exit(0)

    print(f"[*] Found {len(vulnerabilities)} vulnerabilities to analyze")
    analysis    = ask_mistral(vulnerabilities)
    save_html_report(vulnerabilities, analysis)
    print("\n[+] ✅ AI analysis complete!")
